ALTER VIEW "DBA"."topActivePosters"()
AS
//SELECT username, postcounter FROM UZYTKOWNIK WHERE postcounter > (SELECT AVG(postcounter) FROM UZYTKOWNIK)

//z podzialem na watki:

SELECT UZYTKOWNIK.USERNAME, WATEK.TOPIC FROM( //WYNIK
    SELECT X.THREADID, X.USERID FROM( //KOMPLETUJEMY INFORMACJE POSTID+THREADID+USERID+B+C+D STEP:4
        SELECT A.POSTID, A.THREADID, A.USERID, B.POSTPERTHREAD, C.USERPERTHREAD, D.POSTPERUSER FROM POST A
        JOIN
            (SELECT THREADID, COUNT(*) AS POSTPERTHREAD FROM POST GROUP BY THREADID) B //LICZBA POSTÓW W WATKU STEP:1
        ON A.THREADID=B.THREADID
        JOIN
            (SELECT THREADID, COUNT(DISTINCT USERID) AS USERPERTHREAD FROM POST GROUP BY THREADID) C //LICZBA UZYTKOWNIKÓW W WATKU STEP:2
        ON A.THREADID=C.THREADID
        JOIN
            (SELECT THREADID, USERID, COUNT(POSTID) AS POSTPERUSER FROM POST GROUP BY THREADID,USERID) D //LICZBA POSTÓW NA UZYTKOWNIKA W WATKU STEP:3
        ON A.THREADID=D.THREADID AND A.USERID=D.USERID
    ) X WHERE POSTPERUSER>CAST(POSTPERTHREAD AS DECIMAL)/USERPERTHREAD GROUP BY THREADID, USERID //POBIERAMY TYLKO DANE UZYTKOWNIKÓW Z LICZBA POSTÓW POWYZEJ SREDNIEJ STEP:5
) Y, UZYTKOWNIK, WATEK
WHERE Y.USERID=UZYTKOWNIK.USERID AND Y.THREADID=WATEK.THREADID //PRZYPISUJEMY KLUCZE ID WATKÓW I UZYTKOWNIKÓW, ABY OTRZYMAC INFORMACJE ZAMIAST SAMYCH NUMERÓW ID STEP:6